package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AddressFullName implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String x1;
   private java.lang.String x2;
   private java.lang.String x3;

   private java.lang.String x4;

   private java.lang.String financialInstitution;

   private java.lang.String branchInformation;

   private java.lang.String cityName;

   private java.lang.String location;

   private java.lang.String countryCode;

   public AddressFullName()
   {
   }

   public java.lang.String getX1()
   {
      return this.x1;
   }

   public void setX1(java.lang.String x1)
   {
      this.x1 = x1;
   }

   public java.lang.String getX2()
   {
      return this.x2;
   }

   public void setX2(java.lang.String x2)
   {
      this.x2 = x2;
   }

   public java.lang.String getX3()
   {
      return this.x3;
   }

   public void setX3(java.lang.String x3)
   {
      this.x3 = x3;
   }

   public java.lang.String getX4()
   {
      return this.x4;
   }

   public void setX4(java.lang.String x4)
   {
      this.x4 = x4;
   }

   public java.lang.String getFinancialInstitution()
   {
      return this.financialInstitution;
   }

   public void setFinancialInstitution(java.lang.String financialInstitution)
   {
      this.financialInstitution = financialInstitution;
   }

   public java.lang.String getBranchInformation()
   {
      return this.branchInformation;
   }

   public void setBranchInformation(java.lang.String branchInformation)
   {
      this.branchInformation = branchInformation;
   }

   public java.lang.String getCityName()
   {
      return this.cityName;
   }

   public void setCityName(java.lang.String cityName)
   {
      this.cityName = cityName;
   }

   public java.lang.String getLocation()
   {
      return this.location;
   }

   public void setLocation(java.lang.String location)
   {
      this.location = location;
   }

   public java.lang.String getCountryCode()
   {
      return this.countryCode;
   }

   public void setCountryCode(java.lang.String countryCode)
   {
      this.countryCode = countryCode;
   }

   public AddressFullName(java.lang.String x1, java.lang.String x2,
         java.lang.String x3, java.lang.String x4,
         java.lang.String financialInstitution,
         java.lang.String branchInformation, java.lang.String cityName,
         java.lang.String location, java.lang.String countryCode)
   {
      this.x1 = x1;
      this.x2 = x2;
      this.x3 = x3;
      this.x4 = x4;
      this.financialInstitution = financialInstitution;
      this.branchInformation = branchInformation;
      this.cityName = cityName;
      this.location = location;
      this.countryCode = countryCode;
   }

}