package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AddressInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String nickname;
   private enisis.server.exchange.model.pduV202.AddressFullName fullName;

   private java.lang.String bic12;

   private java.lang.String dn;

   public AddressInfo()
   {
   }

   public java.lang.String getNickname()
   {
      return this.nickname;
   }

   public void setNickname(java.lang.String nickname)
   {
      this.nickname = nickname;
   }

   public enisis.server.exchange.model.pduV202.AddressFullName getFullName()
   {
      return this.fullName;
   }

   public void setFullName(
         enisis.server.exchange.model.pduV202.AddressFullName fullName)
   {
      this.fullName = fullName;
   }

   public java.lang.String getBic12()
   {
      return this.bic12;
   }

   public void setBic12(java.lang.String bic12)
   {
      this.bic12 = bic12;
   }

   public java.lang.String getDn()
   {
      return this.dn;
   }

   public void setDn(java.lang.String dn)
   {
      this.dn = dn;
   }

   public AddressInfo(java.lang.String nickname,
         enisis.server.exchange.model.pduV202.AddressFullName fullName,
         java.lang.String bic12, java.lang.String dn)
   {
      this.nickname = nickname;
      this.fullName = fullName;
      this.bic12 = bic12;
      this.dn = dn;
   }

}