package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class DigestList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<enisis.server.exchange.model.pduV202.Digest> digest;

   public DigestList()
   {
   }

   public java.util.List<enisis.server.exchange.model.pduV202.Digest> getDigest()
   {
      return this.digest;
   }

   public void setDigest(
         java.util.List<enisis.server.exchange.model.pduV202.Digest> digest)
   {
      this.digest = digest;
   }

   public DigestList(
         java.util.List<enisis.server.exchange.model.pduV202.Digest> digest)
   {
      this.digest = digest;
   }

}