package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Digest implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String digestRef;
   private java.lang.String digestValue;

   public Digest()
   {
   }

   public java.lang.String getDigestRef()
   {
      return this.digestRef;
   }

   public void setDigestRef(java.lang.String digestRef)
   {
      this.digestRef = digestRef;
   }

   public java.lang.String getDigestValue()
   {
      return this.digestValue;
   }

   public void setDigestValue(java.lang.String digestValue)
   {
      this.digestValue = digestValue;
   }

   public Digest(java.lang.String digestRef, java.lang.String digestValue)
   {
      this.digestRef = digestRef;
      this.digestValue = digestValue;
   }

}