package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String instanceName;
   private java.lang.String userName;
   private java.lang.String unit;
   private java.lang.String network;
   private java.lang.String creationDate;
   private java.lang.Boolean isInternal;
   private java.lang.Boolean isConverted;
   private java.lang.Boolean isCompleted;

   public ExchangeInfo()
   {
   }

   public java.lang.String getInstanceName()
   {
      return this.instanceName;
   }

   public void setInstanceName(java.lang.String instanceName)
   {
      this.instanceName = instanceName;
   }

   public java.lang.String getUserName()
   {
      return this.userName;
   }

   public void setUserName(java.lang.String userName)
   {
      this.userName = userName;
   }

   public java.lang.String getUnit()
   {
      return this.unit;
   }

   public void setUnit(java.lang.String unit)
   {
      this.unit = unit;
   }

   public java.lang.String getNetwork()
   {
      return this.network;
   }

   public void setNetwork(java.lang.String network)
   {
      this.network = network;
   }

   public java.lang.String getCreationDate()
   {
      return this.creationDate;
   }

   public void setCreationDate(java.lang.String creationDate)
   {
      this.creationDate = creationDate;
   }

   public java.lang.Boolean getIsInternal()
   {
      return this.isInternal;
   }

   public void setIsInternal(java.lang.Boolean isInternal)
   {
      this.isInternal = isInternal;
   }

   public java.lang.Boolean getIsConverted()
   {
      return this.isConverted;
   }

   public void setIsConverted(java.lang.Boolean isConverted)
   {
      this.isConverted = isConverted;
   }

   public java.lang.Boolean getIsCompleted()
   {
      return this.isCompleted;
   }

   public void setIsCompleted(java.lang.Boolean isCompleted)
   {
      this.isCompleted = isCompleted;
   }

   public ExchangeInfo(java.lang.String instanceName,
         java.lang.String userName, java.lang.String unit,
         java.lang.String network, java.lang.String creationDate,
         java.lang.Boolean isInternal, java.lang.Boolean isConverted,
         java.lang.Boolean isCompleted)
   {
      this.instanceName = instanceName;
      this.userName = userName;
      this.unit = unit;
      this.network = network;
      this.creationDate = creationDate;
      this.isInternal = isInternal;
      this.isConverted = isConverted;
      this.isCompleted = isCompleted;
   }

}