package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangePDU implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String messageId;
   private java.lang.String groupId;
   private java.lang.Integer groupSeqNr;
   private java.lang.String subscriptionId;
   private java.lang.String revision;
   private java.lang.String timeZone;
   private java.lang.String headerType;
   private enisis.server.exchange.model.pduV202.Body body;
   private java.lang.String lastUpdate;
   private enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction;

   private enisis.server.exchange.model.pduV202.Header header;

   private java.util.List<java.lang.String> recipients;

   public ExchangePDU()
   {
   }

   public java.lang.String getMessageId()
   {
      return this.messageId;
   }

   public void setMessageId(java.lang.String messageId)
   {
      this.messageId = messageId;
   }

   public java.lang.String getGroupId()
   {
      return this.groupId;
   }

   public void setGroupId(java.lang.String groupId)
   {
      this.groupId = groupId;
   }

   public java.lang.Integer getGroupSeqNr()
   {
      return this.groupSeqNr;
   }

   public void setGroupSeqNr(java.lang.Integer groupSeqNr)
   {
      this.groupSeqNr = groupSeqNr;
   }

   public java.lang.String getSubscriptionId()
   {
      return this.subscriptionId;
   }

   public void setSubscriptionId(java.lang.String subscriptionId)
   {
      this.subscriptionId = subscriptionId;
   }

   public java.lang.String getRevision()
   {
      return this.revision;
   }

   public void setRevision(java.lang.String revision)
   {
      this.revision = revision;
   }

   public java.lang.String getTimeZone()
   {
      return this.timeZone;
   }

   public void setTimeZone(java.lang.String timeZone)
   {
      this.timeZone = timeZone;
   }

   public java.lang.String getHeaderType()
   {
      return this.headerType;
   }

   public void setHeaderType(java.lang.String headerType)
   {
      this.headerType = headerType;
   }

   public enisis.server.exchange.model.pduV202.Body getBody()
   {
      return this.body;
   }

   public void setBody(enisis.server.exchange.model.pduV202.Body body)
   {
      this.body = body;
   }

   public java.lang.String getLastUpdate()
   {
      return this.lastUpdate;
   }

   public void setLastUpdate(java.lang.String lastUpdate)
   {
      this.lastUpdate = lastUpdate;
   }

   public enisis.server.exchange.model.pduV202.RoutingInstruction getRoutingInstruction()
   {
      return this.routingInstruction;
   }

   public void setRoutingInstruction(
         enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction)
   {
      this.routingInstruction = routingInstruction;
   }

   public enisis.server.exchange.model.pduV202.Header getHeader()
   {
      return this.header;
   }

   public void setHeader(enisis.server.exchange.model.pduV202.Header header)
   {
      this.header = header;
   }

   public java.util.List<java.lang.String> getRecipients()
   {
      return this.recipients;
   }

   public void setRecipients(java.util.List<java.lang.String> recipients)
   {
      this.recipients = recipients;
   }

   public ExchangePDU(
         java.lang.String messageId,
         java.lang.String groupId,
         java.lang.Integer groupSeqNr,
         java.lang.String subscriptionId,
         java.lang.String revision,
         java.lang.String timeZone,
         java.lang.String headerType,
         enisis.server.exchange.model.pduV202.Body body,
         java.lang.String lastUpdate,
         enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction,
         enisis.server.exchange.model.pduV202.Header header,
         java.util.List<java.lang.String> recipients)
   {
      this.messageId = messageId;
      this.groupId = groupId;
      this.groupSeqNr = groupSeqNr;
      this.subscriptionId = subscriptionId;
      this.revision = revision;
      this.timeZone = timeZone;
      this.headerType = headerType;
      this.body = body;
      this.lastUpdate = lastUpdate;
      this.routingInstruction = routingInstruction;
      this.header = header;
      this.recipients = recipients;
   }

}