package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeNetworkInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String requestType;
   private java.lang.String snlRef;
   private java.lang.String reference;
   private java.lang.String snlEndPoint;
   private java.lang.String snFQueueName;
   private java.lang.String snFInputTime;
   private java.lang.String snFDeliveryTime;
   private java.lang.String creationTime;
   private enisis.server.exchange.model.pduV202.ValidationDescriptor validationDescriptor;
   private java.lang.String responseResponderDN;
   private java.lang.String responseSWIFTRef;
   private java.lang.String responseSNLRef;
   private java.lang.String responseReference;
   private java.lang.Boolean isPossibleDuplicateResponse;
   private enisis.server.exchange.model.pduV202.ResponseValidationDescriptor responseValidationDescriptor;
   private enisis.server.exchange.model.pduV202.PayloadAttributeList payloadAttributes;
   private enisis.server.exchange.model.pduV202.PayloadAttributeList responsePayloadAttributes;
   private java.lang.Boolean isCopyRequested;
   private java.lang.Boolean isAuthNotificationRequested;
   private enisis.server.exchange.model.pduV202.CopyInfo copyInfo;
   private java.lang.String transferRef;
   private java.lang.String storedTransferRef;
   private java.lang.String origSnfRef;
   private java.lang.String transferDescription;
   private java.lang.String transferInfo;
   private java.lang.String fileDescription;
   private java.lang.String fileInfo;
   private enisis.server.exchange.model.pduV202.HeaderInfo headerInfo;
   private java.lang.String notificationResponderDN;
   private java.lang.String notificationRequestType;
   private java.lang.String fileStartTime;
   private java.lang.String fileEndTime;
   private java.lang.String overdueWarningTime;
   private java.lang.Integer overdueWarningDelay;

   private java.lang.String hubRef;

   public ExchangeNetworkInfo()
   {
   }

   public java.lang.String getRequestType()
   {
      return this.requestType;
   }

   public void setRequestType(java.lang.String requestType)
   {
      this.requestType = requestType;
   }

   public java.lang.String getSnlRef()
   {
      return this.snlRef;
   }

   public void setSnlRef(java.lang.String snlRef)
   {
      this.snlRef = snlRef;
   }

   public java.lang.String getReference()
   {
      return this.reference;
   }

   public void setReference(java.lang.String reference)
   {
      this.reference = reference;
   }

   public java.lang.String getSnlEndPoint()
   {
      return this.snlEndPoint;
   }

   public void setSnlEndPoint(java.lang.String snlEndPoint)
   {
      this.snlEndPoint = snlEndPoint;
   }

   public java.lang.String getSnFQueueName()
   {
      return this.snFQueueName;
   }

   public void setSnFQueueName(java.lang.String snFQueueName)
   {
      this.snFQueueName = snFQueueName;
   }

   public java.lang.String getSnFInputTime()
   {
      return this.snFInputTime;
   }

   public void setSnFInputTime(java.lang.String snFInputTime)
   {
      this.snFInputTime = snFInputTime;
   }

   public java.lang.String getSnFDeliveryTime()
   {
      return this.snFDeliveryTime;
   }

   public void setSnFDeliveryTime(java.lang.String snFDeliveryTime)
   {
      this.snFDeliveryTime = snFDeliveryTime;
   }

   public java.lang.String getCreationTime()
   {
      return this.creationTime;
   }

   public void setCreationTime(java.lang.String creationTime)
   {
      this.creationTime = creationTime;
   }

   public enisis.server.exchange.model.pduV202.ValidationDescriptor getValidationDescriptor()
   {
      return this.validationDescriptor;
   }

   public void setValidationDescriptor(
         enisis.server.exchange.model.pduV202.ValidationDescriptor validationDescriptor)
   {
      this.validationDescriptor = validationDescriptor;
   }

   public java.lang.String getResponseResponderDN()
   {
      return this.responseResponderDN;
   }

   public void setResponseResponderDN(java.lang.String responseResponderDN)
   {
      this.responseResponderDN = responseResponderDN;
   }

   public java.lang.String getResponseSWIFTRef()
   {
      return this.responseSWIFTRef;
   }

   public void setResponseSWIFTRef(java.lang.String responseSWIFTRef)
   {
      this.responseSWIFTRef = responseSWIFTRef;
   }

   public java.lang.String getResponseSNLRef()
   {
      return this.responseSNLRef;
   }

   public void setResponseSNLRef(java.lang.String responseSNLRef)
   {
      this.responseSNLRef = responseSNLRef;
   }

   public java.lang.String getResponseReference()
   {
      return this.responseReference;
   }

   public void setResponseReference(java.lang.String responseReference)
   {
      this.responseReference = responseReference;
   }

   public java.lang.Boolean getIsPossibleDuplicateResponse()
   {
      return this.isPossibleDuplicateResponse;
   }

   public void setIsPossibleDuplicateResponse(
         java.lang.Boolean isPossibleDuplicateResponse)
   {
      this.isPossibleDuplicateResponse = isPossibleDuplicateResponse;
   }

   public enisis.server.exchange.model.pduV202.ResponseValidationDescriptor getResponseValidationDescriptor()
   {
      return this.responseValidationDescriptor;
   }

   public void setResponseValidationDescriptor(
         enisis.server.exchange.model.pduV202.ResponseValidationDescriptor responseValidationDescriptor)
   {
      this.responseValidationDescriptor = responseValidationDescriptor;
   }

   public enisis.server.exchange.model.pduV202.PayloadAttributeList getPayloadAttributes()
   {
      return this.payloadAttributes;
   }

   public void setPayloadAttributes(
         enisis.server.exchange.model.pduV202.PayloadAttributeList payloadAttributes)
   {
      this.payloadAttributes = payloadAttributes;
   }

   public enisis.server.exchange.model.pduV202.PayloadAttributeList getResponsePayloadAttributes()
   {
      return this.responsePayloadAttributes;
   }

   public void setResponsePayloadAttributes(
         enisis.server.exchange.model.pduV202.PayloadAttributeList responsePayloadAttributes)
   {
      this.responsePayloadAttributes = responsePayloadAttributes;
   }

   public java.lang.Boolean getIsCopyRequested()
   {
      return this.isCopyRequested;
   }

   public void setIsCopyRequested(java.lang.Boolean isCopyRequested)
   {
      this.isCopyRequested = isCopyRequested;
   }

   public java.lang.Boolean getIsAuthNotificationRequested()
   {
      return this.isAuthNotificationRequested;
   }

   public void setIsAuthNotificationRequested(
         java.lang.Boolean isAuthNotificationRequested)
   {
      this.isAuthNotificationRequested = isAuthNotificationRequested;
   }

   public enisis.server.exchange.model.pduV202.CopyInfo getCopyInfo()
   {
      return this.copyInfo;
   }

   public void setCopyInfo(
         enisis.server.exchange.model.pduV202.CopyInfo copyInfo)
   {
      this.copyInfo = copyInfo;
   }

   public java.lang.String getTransferRef()
   {
      return this.transferRef;
   }

   public void setTransferRef(java.lang.String transferRef)
   {
      this.transferRef = transferRef;
   }

   public java.lang.String getStoredTransferRef()
   {
      return this.storedTransferRef;
   }

   public void setStoredTransferRef(java.lang.String storedTransferRef)
   {
      this.storedTransferRef = storedTransferRef;
   }

   public java.lang.String getOrigSnfRef()
   {
      return this.origSnfRef;
   }

   public void setOrigSnfRef(java.lang.String origSnfRef)
   {
      this.origSnfRef = origSnfRef;
   }

   public java.lang.String getTransferDescription()
   {
      return this.transferDescription;
   }

   public void setTransferDescription(java.lang.String transferDescription)
   {
      this.transferDescription = transferDescription;
   }

   public java.lang.String getTransferInfo()
   {
      return this.transferInfo;
   }

   public void setTransferInfo(java.lang.String transferInfo)
   {
      this.transferInfo = transferInfo;
   }

   public java.lang.String getFileDescription()
   {
      return this.fileDescription;
   }

   public void setFileDescription(java.lang.String fileDescription)
   {
      this.fileDescription = fileDescription;
   }

   public java.lang.String getFileInfo()
   {
      return this.fileInfo;
   }

   public void setFileInfo(java.lang.String fileInfo)
   {
      this.fileInfo = fileInfo;
   }

   public enisis.server.exchange.model.pduV202.HeaderInfo getHeaderInfo()
   {
      return this.headerInfo;
   }

   public void setHeaderInfo(
         enisis.server.exchange.model.pduV202.HeaderInfo headerInfo)
   {
      this.headerInfo = headerInfo;
   }

   public java.lang.String getNotificationResponderDN()
   {
      return this.notificationResponderDN;
   }

   public void setNotificationResponderDN(
         java.lang.String notificationResponderDN)
   {
      this.notificationResponderDN = notificationResponderDN;
   }

   public java.lang.String getNotificationRequestType()
   {
      return this.notificationRequestType;
   }

   public void setNotificationRequestType(
         java.lang.String notificationRequestType)
   {
      this.notificationRequestType = notificationRequestType;
   }

   public java.lang.String getFileStartTime()
   {
      return this.fileStartTime;
   }

   public void setFileStartTime(java.lang.String fileStartTime)
   {
      this.fileStartTime = fileStartTime;
   }

   public java.lang.String getFileEndTime()
   {
      return this.fileEndTime;
   }

   public void setFileEndTime(java.lang.String fileEndTime)
   {
      this.fileEndTime = fileEndTime;
   }

   public java.lang.String getOverdueWarningTime()
   {
      return this.overdueWarningTime;
   }

   public void setOverdueWarningTime(java.lang.String overdueWarningTime)
   {
      this.overdueWarningTime = overdueWarningTime;
   }

   public java.lang.Integer getOverdueWarningDelay()
   {
      return this.overdueWarningDelay;
   }

   public void setOverdueWarningDelay(java.lang.Integer overdueWarningDelay)
   {
      this.overdueWarningDelay = overdueWarningDelay;
   }

   public java.lang.String getHubRef()
   {
      return this.hubRef;
   }

   public void setHubRef(java.lang.String hubRef)
   {
      this.hubRef = hubRef;
   }

   public ExchangeNetworkInfo(
         java.lang.String requestType,
         java.lang.String snlRef,
         java.lang.String reference,
         java.lang.String snlEndPoint,
         java.lang.String snFQueueName,
         java.lang.String snFInputTime,
         java.lang.String snFDeliveryTime,
         java.lang.String creationTime,
         enisis.server.exchange.model.pduV202.ValidationDescriptor validationDescriptor,
         java.lang.String responseResponderDN,
         java.lang.String responseSWIFTRef,
         java.lang.String responseSNLRef,
         java.lang.String responseReference,
         java.lang.Boolean isPossibleDuplicateResponse,
         enisis.server.exchange.model.pduV202.ResponseValidationDescriptor responseValidationDescriptor,
         enisis.server.exchange.model.pduV202.PayloadAttributeList payloadAttributes,
         enisis.server.exchange.model.pduV202.PayloadAttributeList responsePayloadAttributes,
         java.lang.Boolean isCopyRequested,
         java.lang.Boolean isAuthNotificationRequested,
         enisis.server.exchange.model.pduV202.CopyInfo copyInfo,
         java.lang.String transferRef, java.lang.String storedTransferRef,
         java.lang.String origSnfRef, java.lang.String transferDescription,
         java.lang.String transferInfo, java.lang.String fileDescription,
         java.lang.String fileInfo,
         enisis.server.exchange.model.pduV202.HeaderInfo headerInfo,
         java.lang.String notificationResponderDN,
         java.lang.String notificationRequestType,
         java.lang.String fileStartTime, java.lang.String fileEndTime,
         java.lang.String overdueWarningTime,
         java.lang.Integer overdueWarningDelay, java.lang.String hubRef)
   {
      this.requestType = requestType;
      this.snlRef = snlRef;
      this.reference = reference;
      this.snlEndPoint = snlEndPoint;
      this.snFQueueName = snFQueueName;
      this.snFInputTime = snFInputTime;
      this.snFDeliveryTime = snFDeliveryTime;
      this.creationTime = creationTime;
      this.validationDescriptor = validationDescriptor;
      this.responseResponderDN = responseResponderDN;
      this.responseSWIFTRef = responseSWIFTRef;
      this.responseSNLRef = responseSNLRef;
      this.responseReference = responseReference;
      this.isPossibleDuplicateResponse = isPossibleDuplicateResponse;
      this.responseValidationDescriptor = responseValidationDescriptor;
      this.payloadAttributes = payloadAttributes;
      this.responsePayloadAttributes = responsePayloadAttributes;
      this.isCopyRequested = isCopyRequested;
      this.isAuthNotificationRequested = isAuthNotificationRequested;
      this.copyInfo = copyInfo;
      this.transferRef = transferRef;
      this.storedTransferRef = storedTransferRef;
      this.origSnfRef = origSnfRef;
      this.transferDescription = transferDescription;
      this.transferInfo = transferInfo;
      this.fileDescription = fileDescription;
      this.fileInfo = fileInfo;
      this.headerInfo = headerInfo;
      this.notificationResponderDN = notificationResponderDN;
      this.notificationRequestType = notificationRequestType;
      this.fileStartTime = fileStartTime;
      this.fileEndTime = fileEndTime;
      this.overdueWarningTime = overdueWarningTime;
      this.overdueWarningDelay = overdueWarningDelay;
      this.hubRef = hubRef;
   }

}