package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class ExchangeSecurityInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean isNRRequested;
   private java.lang.String signerDN;
   private java.lang.String nrType;
   private java.lang.String nrWarning;
   private java.lang.String signatureResult;

   private enisis.server.exchange.model.pduV202.SignatureValue signatureValue;

   private String responseNRType;

   private java.lang.String responseNRWarning;

   private java.lang.String responseSignatureResult;

   private enisis.server.exchange.model.pduV202.ResponseSignatureValue responseSignatureValue;

   private java.lang.String fileDigestAlgorithm;

   private java.lang.String fileDigestValue;

   private enisis.server.exchange.model.pduV202.DigestList digestList;

   private java.lang.String thirdPartySignerDN;

   public ExchangeSecurityInfo()
   {
   }

   public java.lang.Boolean getIsNRRequested()
   {
      return this.isNRRequested;
   }

   public void setIsNRRequested(java.lang.Boolean isNRRequested)
   {
      this.isNRRequested = isNRRequested;
   }

   public java.lang.String getSignerDN()
   {
      return this.signerDN;
   }

   public void setSignerDN(java.lang.String signerDN)
   {
      this.signerDN = signerDN;
   }

   public java.lang.String getNrType()
   {
      return this.nrType;
   }

   public void setNrType(java.lang.String nrType)
   {
      this.nrType = nrType;
   }

   public java.lang.String getNrWarning()
   {
      return this.nrWarning;
   }

   public void setNrWarning(java.lang.String nrWarning)
   {
      this.nrWarning = nrWarning;
   }

   public java.lang.String getSignatureResult()
   {
      return this.signatureResult;
   }

   public void setSignatureResult(java.lang.String signatureResult)
   {
      this.signatureResult = signatureResult;
   }

   public enisis.server.exchange.model.pduV202.SignatureValue getSignatureValue()
   {
      return this.signatureValue;
   }

   public void setSignatureValue(
         enisis.server.exchange.model.pduV202.SignatureValue signatureValue)
   {
      this.signatureValue = signatureValue;
   }

   public java.lang.String getResponseNRWarning()
   {
      return this.responseNRWarning;
   }

   public void setResponseNRWarning(java.lang.String responseNRWarning)
   {
      this.responseNRWarning = responseNRWarning;
   }

   public java.lang.String getResponseSignatureResult()
   {
      return this.responseSignatureResult;
   }

   public void setResponseSignatureResult(java.lang.String responseSignatureResult)
   {
      this.responseSignatureResult = responseSignatureResult;
   }

   public enisis.server.exchange.model.pduV202.ResponseSignatureValue getResponseSignatureValue()
   {
      return this.responseSignatureValue;
   }

   public void setResponseSignatureValue(
         enisis.server.exchange.model.pduV202.ResponseSignatureValue responseSignatureValue)
   {
      this.responseSignatureValue = responseSignatureValue;
   }

   public java.lang.String getFileDigestAlgorithm()
   {
      return this.fileDigestAlgorithm;
   }

   public void setFileDigestAlgorithm(java.lang.String fileDigestAlgorithm)
   {
      this.fileDigestAlgorithm = fileDigestAlgorithm;
   }

   public java.lang.String getFileDigestValue()
   {
      return this.fileDigestValue;
   }

   public void setFileDigestValue(java.lang.String fileDigestValue)
   {
      this.fileDigestValue = fileDigestValue;
   }

   public enisis.server.exchange.model.pduV202.DigestList getDigestList()
   {
      return this.digestList;
   }

   public void setDigestList(
         enisis.server.exchange.model.pduV202.DigestList digestList)
   {
      this.digestList = digestList;
   }

   public java.lang.String getThirdPartySignerDN()
   {
      return this.thirdPartySignerDN;
   }

   public void setThirdPartySignerDN(java.lang.String thirdPartySignerDN)
   {
      this.thirdPartySignerDN = thirdPartySignerDN;
   }

   public java.lang.String getResponseNRType()
   {
      return this.responseNRType;
   }

   public void setResponseNRType(java.lang.String responseNRType)
   {
      this.responseNRType = responseNRType;
   }

   public ExchangeSecurityInfo(
         java.lang.Boolean isNRRequested,
         java.lang.String signerDN,
         java.lang.String nrType,
         java.lang.String nrWarning,
         java.lang.String signatureResult,
         enisis.server.exchange.model.pduV202.SignatureValue signatureValue,
         java.lang.String responseNRType,
         java.lang.String responseNRWarning,
         java.lang.String responseSignatureResult,
         enisis.server.exchange.model.pduV202.ResponseSignatureValue responseSignatureValue,
         java.lang.String fileDigestAlgorithm, java.lang.String fileDigestValue,
         enisis.server.exchange.model.pduV202.DigestList digestList,
         java.lang.String thirdPartySignerDN)
   {
      this.isNRRequested = isNRRequested;
      this.signerDN = signerDN;
      this.nrType = nrType;
      this.nrWarning = nrWarning;
      this.signatureResult = signatureResult;
      this.signatureValue = signatureValue;
      this.responseNRType = responseNRType;
      this.responseNRWarning = responseNRWarning;
      this.responseSignatureResult = responseSignatureResult;
      this.responseSignatureValue = responseSignatureValue;
      this.fileDigestAlgorithm = fileDigestAlgorithm;
      this.fileDigestValue = fileDigestValue;
      this.digestList = digestList;
      this.thirdPartySignerDN = thirdPartySignerDN;
   }

}