package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Header implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private enisis.server.exchange.model.pduV202.Message message;
   private enisis.server.exchange.model.pduV202.TransmissionReport transmissionReport;
   private enisis.server.exchange.model.pduV202.DeliveryNotification deliveryNotification;
   private enisis.server.exchange.model.pduV202.DeliveryReport deliveryReport;
   private enisis.server.exchange.model.pduV202.HistoryReport historyReport;
   private enisis.server.exchange.model.pduV202.SessionStatus sessionStatus;
   private enisis.server.exchange.model.pduV202.MessageStatus messageStatus;

   public Header()
   {
   }

   public enisis.server.exchange.model.pduV202.Message getMessage()
   {
      return this.message;
   }

   public void setMessage(enisis.server.exchange.model.pduV202.Message message)
   {
      this.message = message;
   }

   public enisis.server.exchange.model.pduV202.TransmissionReport getTransmissionReport()
   {
      return this.transmissionReport;
   }

   public void setTransmissionReport(
         enisis.server.exchange.model.pduV202.TransmissionReport transmissionReport)
   {
      this.transmissionReport = transmissionReport;
   }

   public enisis.server.exchange.model.pduV202.DeliveryNotification getDeliveryNotification()
   {
      return this.deliveryNotification;
   }

   public void setDeliveryNotification(
         enisis.server.exchange.model.pduV202.DeliveryNotification deliveryNotification)
   {
      this.deliveryNotification = deliveryNotification;
   }

   public enisis.server.exchange.model.pduV202.DeliveryReport getDeliveryReport()
   {
      return this.deliveryReport;
   }

   public void setDeliveryReport(
         enisis.server.exchange.model.pduV202.DeliveryReport deliveryReport)
   {
      this.deliveryReport = deliveryReport;
   }

   public enisis.server.exchange.model.pduV202.HistoryReport getHistoryReport()
   {
      return this.historyReport;
   }

   public void setHistoryReport(
         enisis.server.exchange.model.pduV202.HistoryReport historyReport)
   {
      this.historyReport = historyReport;
   }

   public enisis.server.exchange.model.pduV202.SessionStatus getSessionStatus()
   {
      return this.sessionStatus;
   }

   public void setSessionStatus(
         enisis.server.exchange.model.pduV202.SessionStatus sessionStatus)
   {
      this.sessionStatus = sessionStatus;
   }

   public enisis.server.exchange.model.pduV202.MessageStatus getMessageStatus()
   {
      return this.messageStatus;
   }

   public void setMessageStatus(
         enisis.server.exchange.model.pduV202.MessageStatus messageStatus)
   {
      this.messageStatus = messageStatus;
   }

   public Header(
         enisis.server.exchange.model.pduV202.Message message,
         enisis.server.exchange.model.pduV202.TransmissionReport transmissionReport,
         enisis.server.exchange.model.pduV202.DeliveryNotification deliveryNotification,
         enisis.server.exchange.model.pduV202.DeliveryReport deliveryReport,
         enisis.server.exchange.model.pduV202.HistoryReport historyReport,
         enisis.server.exchange.model.pduV202.SessionStatus sessionStatus,
         enisis.server.exchange.model.pduV202.MessageStatus messageStatus)
   {
      this.message = message;
      this.transmissionReport = transmissionReport;
      this.deliveryNotification = deliveryNotification;
      this.deliveryReport = deliveryReport;
      this.historyReport = historyReport;
      this.sessionStatus = sessionStatus;
      this.messageStatus = messageStatus;
   }

}