package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HistoryInterventions implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<enisis.server.exchange.model.pduV202.HistoryIntervention> intervention;

   private java.lang.Integer comparator;

   public HistoryInterventions()
   {
   }

   public java.util.List<enisis.server.exchange.model.pduV202.HistoryIntervention> getIntervention()
   {
      return this.intervention;
   }

   public void setIntervention(
         java.util.List<enisis.server.exchange.model.pduV202.HistoryIntervention> intervention)
   {
      this.intervention = intervention;
   }

   public java.lang.Integer getComparator()
   {
      return this.comparator;
   }

   public void setComparator(java.lang.Integer comparator)
   {
      this.comparator = comparator;
   }

   public HistoryInterventions(
         java.util.List<enisis.server.exchange.model.pduV202.HistoryIntervention> intervention,
         java.lang.Integer comparator)
   {
      this.intervention = intervention;
      this.comparator = comparator;
   }

}