package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class HistoryIntervention implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String intvCategory;
   private java.lang.String creationTime;
   private java.lang.String operatorOrigin;
   private java.lang.String text;

   public HistoryIntervention()
   {
   }

   public java.lang.String getIntvCategory()
   {
      return this.intvCategory;
   }

   public void setIntvCategory(java.lang.String intvCategory)
   {
      this.intvCategory = intvCategory;
   }

   public java.lang.String getCreationTime()
   {
      return this.creationTime;
   }

   public void setCreationTime(java.lang.String creationTime)
   {
      this.creationTime = creationTime;
   }

   public java.lang.String getOperatorOrigin()
   {
      return this.operatorOrigin;
   }

   public void setOperatorOrigin(java.lang.String operatorOrigin)
   {
      this.operatorOrigin = operatorOrigin;
   }

   public java.lang.String getText()
   {
      return this.text;
   }

   public void setText(java.lang.String text)
   {
      this.text = text;
   }

   public HistoryIntervention(java.lang.String intvCategory,
         java.lang.String creationTime, java.lang.String operatorOrigin,
         java.lang.String text)
   {
      this.intvCategory = intvCategory;
      this.creationTime = creationTime;
      this.operatorOrigin = operatorOrigin;
      this.text = text;
   }

}