package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class InterfaceInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String userReference;
   private java.lang.String routingCode;
   private String validationLevel;
   private java.lang.Boolean isModificationAllowed;
   private enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction;
   private String messageCreator;
   private String messageContext;
   private String messageNature;
   private enisis.server.exchange.model.pduV202.ProductList productInfo;

   public InterfaceInfo()
   {
   }

   public java.lang.String getUserReference()
   {
      return this.userReference;
   }

   public void setUserReference(java.lang.String userReference)
   {
      this.userReference = userReference;
   }

   public java.lang.String getRoutingCode()
   {
      return this.routingCode;
   }

   public void setRoutingCode(java.lang.String routingCode)
   {
      this.routingCode = routingCode;
   }

   public java.lang.Boolean getIsModificationAllowed()
   {
      return this.isModificationAllowed;
   }

   public void setIsModificationAllowed(java.lang.Boolean isModificationAllowed)
   {
      this.isModificationAllowed = isModificationAllowed;
   }

   public enisis.server.exchange.model.pduV202.RoutingInstruction getRoutingInstruction()
   {
      return this.routingInstruction;
   }

   public void setRoutingInstruction(
         enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction)
   {
      this.routingInstruction = routingInstruction;
   }

   public enisis.server.exchange.model.pduV202.ProductList getProductInfo()
   {
      return this.productInfo;
   }

   public void setProductInfo(
         enisis.server.exchange.model.pduV202.ProductList productInfo)
   {
      this.productInfo = productInfo;
   }

   public java.lang.String getValidationLevel()
   {
      return this.validationLevel;
   }

   public void setValidationLevel(java.lang.String validationLevel)
   {
      this.validationLevel = validationLevel;
   }

   public java.lang.String getMessageCreator()
   {
      return this.messageCreator;
   }

   public void setMessageCreator(java.lang.String messageCreator)
   {
      this.messageCreator = messageCreator;
   }

   public java.lang.String getMessageContext()
   {
      return this.messageContext;
   }

   public void setMessageContext(java.lang.String messageContext)
   {
      this.messageContext = messageContext;
   }

   public java.lang.String getMessageNature()
   {
      return this.messageNature;
   }

   public void setMessageNature(java.lang.String messageNature)
   {
      this.messageNature = messageNature;
   }

   public InterfaceInfo(
         java.lang.String userReference,
         java.lang.String routingCode,
         java.lang.String validationLevel,
         java.lang.Boolean isModificationAllowed,
         enisis.server.exchange.model.pduV202.RoutingInstruction routingInstruction,
         java.lang.String messageCreator, java.lang.String messageContext,
         java.lang.String messageNature,
         enisis.server.exchange.model.pduV202.ProductList productInfo)
   {
      this.userReference = userReference;
      this.routingCode = routingCode;
      this.validationLevel = validationLevel;
      this.isModificationAllowed = isModificationAllowed;
      this.routingInstruction = routingInstruction;
      this.messageCreator = messageCreator;
      this.messageContext = messageContext;
      this.messageNature = messageNature;
      this.productInfo = productInfo;
   }

}