package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Interventions implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<enisis.server.exchange.model.pduV202.Intervention> intervention;
   private java.lang.Integer comparator;

   public Interventions()
   {
   }

   public java.util.List<enisis.server.exchange.model.pduV202.Intervention> getIntervention()
   {
      return this.intervention;
   }

   public void setIntervention(
         java.util.List<enisis.server.exchange.model.pduV202.Intervention> intervention)
   {
      this.intervention = intervention;
   }

   public java.lang.Integer getComparator()
   {
      return this.comparator;
   }

   public void setComparator(java.lang.Integer comparator)
   {
      this.comparator = comparator;
   }

   public Interventions(
         java.util.List<enisis.server.exchange.model.pduV202.Intervention> intervention,
         java.lang.Integer comparator)
   {
      this.intervention = intervention;
      this.comparator = comparator;
   }

}