package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Message implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String senderReference;
   private java.lang.String relatedReference;
   private java.lang.String messageIdentifier;
   private java.lang.String format;
   private java.lang.String subFormat;
   private enisis.server.exchange.model.pduV202.AddressInfo sender;
   private enisis.server.exchange.model.pduV202.AddressInfo receiver;
   private enisis.server.exchange.model.pduV202.InterfaceInfo interfaceInfo;
   private enisis.server.exchange.model.pduV202.NetworkInfo networkInfo;
   private enisis.server.exchange.model.pduV202.SecurityInfo securityInfo;
   private enisis.server.exchange.model.pduV202.ExchangeInfo exchangeInfo;
   private java.lang.String fileLogicalName;
   private java.lang.Boolean isDirty;

   public Message()
   {
   }

   public java.lang.String getSenderReference()
   {
      return this.senderReference;
   }

   public void setSenderReference(java.lang.String senderReference)
   {
      this.senderReference = senderReference;
   }

   public java.lang.String getRelatedReference()
   {
      return this.relatedReference;
   }

   public void setRelatedReference(java.lang.String relatedReference)
   {
      this.relatedReference = relatedReference;
   }

   public java.lang.String getMessageIdentifier()
   {
      return this.messageIdentifier;
   }

   public void setMessageIdentifier(java.lang.String messageIdentifier)
   {
      this.messageIdentifier = messageIdentifier;
   }

   public java.lang.String getFormat()
   {
      return this.format;
   }

   public void setFormat(java.lang.String format)
   {
      this.format = format;
   }

   public java.lang.String getSubFormat()
   {
      return this.subFormat;
   }

   public void setSubFormat(java.lang.String subFormat)
   {
      this.subFormat = subFormat;
   }

   public enisis.server.exchange.model.pduV202.AddressInfo getSender()
   {
      return this.sender;
   }

   public void setSender(
         enisis.server.exchange.model.pduV202.AddressInfo sender)
   {
      this.sender = sender;
   }

   public enisis.server.exchange.model.pduV202.AddressInfo getReceiver()
   {
      return this.receiver;
   }

   public void setReceiver(
         enisis.server.exchange.model.pduV202.AddressInfo receiver)
   {
      this.receiver = receiver;
   }

   public enisis.server.exchange.model.pduV202.InterfaceInfo getInterfaceInfo()
   {
      return this.interfaceInfo;
   }

   public void setInterfaceInfo(
         enisis.server.exchange.model.pduV202.InterfaceInfo interfaceInfo)
   {
      this.interfaceInfo = interfaceInfo;
   }

   public enisis.server.exchange.model.pduV202.NetworkInfo getNetworkInfo()
   {
      return this.networkInfo;
   }

   public void setNetworkInfo(
         enisis.server.exchange.model.pduV202.NetworkInfo networkInfo)
   {
      this.networkInfo = networkInfo;
   }

   public enisis.server.exchange.model.pduV202.SecurityInfo getSecurityInfo()
   {
      return this.securityInfo;
   }

   public void setSecurityInfo(
         enisis.server.exchange.model.pduV202.SecurityInfo securityInfo)
   {
      this.securityInfo = securityInfo;
   }

   public enisis.server.exchange.model.pduV202.ExchangeInfo getExchangeInfo()
   {
      return this.exchangeInfo;
   }

   public void setExchangeInfo(
         enisis.server.exchange.model.pduV202.ExchangeInfo exchangeInfo)
   {
      this.exchangeInfo = exchangeInfo;
   }

   public java.lang.String getFileLogicalName()
   {
      return this.fileLogicalName;
   }

   public void setFileLogicalName(java.lang.String fileLogicalName)
   {
      this.fileLogicalName = fileLogicalName;
   }

   public java.lang.Boolean getIsDirty()
   {
      return this.isDirty;
   }

   public void setIsDirty(java.lang.Boolean isDirty)
   {
      this.isDirty = isDirty;
   }

   public Message(java.lang.String senderReference,
         java.lang.String relatedReference,
         java.lang.String messageIdentifier, java.lang.String format,
         java.lang.String subFormat,
         enisis.server.exchange.model.pduV202.AddressInfo sender,
         enisis.server.exchange.model.pduV202.AddressInfo receiver,
         enisis.server.exchange.model.pduV202.InterfaceInfo interfaceInfo,
         enisis.server.exchange.model.pduV202.NetworkInfo networkInfo,
         enisis.server.exchange.model.pduV202.SecurityInfo securityInfo,
         enisis.server.exchange.model.pduV202.ExchangeInfo exchangeInfo,
         java.lang.String fileLogicalName, java.lang.Boolean isDirty)
   {
      this.senderReference = senderReference;
      this.relatedReference = relatedReference;
      this.messageIdentifier = messageIdentifier;
      this.format = format;
      this.subFormat = subFormat;
      this.sender = sender;
      this.receiver = receiver;
      this.interfaceInfo = interfaceInfo;
      this.networkInfo = networkInfo;
      this.securityInfo = securityInfo;
      this.exchangeInfo = exchangeInfo;
      this.fileLogicalName = fileLogicalName;
      this.isDirty = isDirty;
   }

}