package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class NetworkInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String priority;
   private java.lang.Boolean isPossibleDuplicate;
   private enisis.server.exchange.model.pduV202.PDEPDM duplicateHistory;
   private java.lang.Boolean isNotificationRequested;
   private java.lang.String service;
   private java.lang.String network;
   private java.lang.Integer originalSessionNr;
   private java.lang.Integer sessionNr;
   private java.lang.String originalSeqNr;
   private java.lang.Integer seqNr;
   private enisis.server.exchange.model.pduV202.FINNetworkInfo finNetworkInfo;
   private enisis.server.exchange.model.pduV202.ExchangeNetworkInfo exchangeNetworkInfo;

   public NetworkInfo()
   {
   }

   public java.lang.Boolean getIsPossibleDuplicate()
   {
      return this.isPossibleDuplicate;
   }

   public void setIsPossibleDuplicate(java.lang.Boolean isPossibleDuplicate)
   {
      this.isPossibleDuplicate = isPossibleDuplicate;
   }

   public enisis.server.exchange.model.pduV202.PDEPDM getDuplicateHistory()
   {
      return this.duplicateHistory;
   }

   public void setDuplicateHistory(
         enisis.server.exchange.model.pduV202.PDEPDM duplicateHistory)
   {
      this.duplicateHistory = duplicateHistory;
   }

   public java.lang.Boolean getIsNotificationRequested()
   {
      return this.isNotificationRequested;
   }

   public void setIsNotificationRequested(
         java.lang.Boolean isNotificationRequested)
   {
      this.isNotificationRequested = isNotificationRequested;
   }

   public java.lang.String getService()
   {
      return this.service;
   }

   public void setService(java.lang.String service)
   {
      this.service = service;
   }

   public java.lang.String getNetwork()
   {
      return this.network;
   }

   public void setNetwork(java.lang.String network)
   {
      this.network = network;
   }

   public java.lang.Integer getOriginalSessionNr()
   {
      return this.originalSessionNr;
   }

   public void setOriginalSessionNr(java.lang.Integer originalSessionNr)
   {
      this.originalSessionNr = originalSessionNr;
   }

   public java.lang.Integer getSessionNr()
   {
      return this.sessionNr;
   }

   public void setSessionNr(java.lang.Integer sessionNr)
   {
      this.sessionNr = sessionNr;
   }

   public java.lang.String getOriginalSeqNr()
   {
      return this.originalSeqNr;
   }

   public void setOriginalSeqNr(java.lang.String originalSeqNr)
   {
      this.originalSeqNr = originalSeqNr;
   }

   public java.lang.Integer getSeqNr()
   {
      return this.seqNr;
   }

   public void setSeqNr(java.lang.Integer seqNr)
   {
      this.seqNr = seqNr;
   }

   public enisis.server.exchange.model.pduV202.FINNetworkInfo getFinNetworkInfo()
   {
      return this.finNetworkInfo;
   }

   public void setFinNetworkInfo(
         enisis.server.exchange.model.pduV202.FINNetworkInfo finNetworkInfo)
   {
      this.finNetworkInfo = finNetworkInfo;
   }

   public enisis.server.exchange.model.pduV202.ExchangeNetworkInfo getExchangeNetworkInfo()
   {
      return this.exchangeNetworkInfo;
   }

   public void setExchangeNetworkInfo(
         enisis.server.exchange.model.pduV202.ExchangeNetworkInfo exchangeNetworkInfo)
   {
      this.exchangeNetworkInfo = exchangeNetworkInfo;
   }

   public java.lang.String getPriority()
   {
      return this.priority;
   }

   public void setPriority(java.lang.String priority)
   {
      this.priority = priority;
   }

   public NetworkInfo(
         java.lang.String priority,
         java.lang.Boolean isPossibleDuplicate,
         enisis.server.exchange.model.pduV202.PDEPDM duplicateHistory,
         java.lang.Boolean isNotificationRequested,
         java.lang.String service,
         java.lang.String network,
         java.lang.Integer originalSessionNr,
         java.lang.Integer sessionNr,
         java.lang.String originalSeqNr,
         java.lang.Integer seqNr,
         enisis.server.exchange.model.pduV202.FINNetworkInfo finNetworkInfo,
         enisis.server.exchange.model.pduV202.ExchangeNetworkInfo exchangeNetworkInfo)
   {
      this.priority = priority;
      this.isPossibleDuplicate = isPossibleDuplicate;
      this.duplicateHistory = duplicateHistory;
      this.isNotificationRequested = isNotificationRequested;
      this.service = service;
      this.network = network;
      this.originalSessionNr = originalSessionNr;
      this.sessionNr = sessionNr;
      this.originalSeqNr = originalSeqNr;
      this.seqNr = seqNr;
      this.finNetworkInfo = finNetworkInfo;
      this.exchangeNetworkInfo = exchangeNetworkInfo;
   }

}