package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PAC2SignatureValue implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> PAC2SignatureValue;

   public PAC2SignatureValue()
   {
   }

   public java.util.List<java.lang.String> getPAC2SignatureValue()
   {
      return this.PAC2SignatureValue;
   }

   public void setPAC2SignatureValue(
         java.util.List<java.lang.String> PAC2SignatureValue)
   {
      this.PAC2SignatureValue = PAC2SignatureValue;
   }

   public PAC2SignatureValue(
         java.util.List<java.lang.String> PAC2SignatureValue)
   {
      this.PAC2SignatureValue = PAC2SignatureValue;
   }

}