package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PayloadAttributeList implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<enisis.server.exchange.model.pduV202.PayloadAttribute> payloadAttribute;

   public PayloadAttributeList()
   {
   }

   public java.util.List<enisis.server.exchange.model.pduV202.PayloadAttribute> getPayloadAttribute()
   {
      return this.payloadAttribute;
   }

   public void setPayloadAttribute(
         java.util.List<enisis.server.exchange.model.pduV202.PayloadAttribute> payloadAttribute)
   {
      this.payloadAttribute = payloadAttribute;
   }

   public PayloadAttributeList(
         java.util.List<enisis.server.exchange.model.pduV202.PayloadAttribute> payloadAttribute)
   {
      this.payloadAttribute = payloadAttribute;
   }

}