package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class PDEPDM implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> pdeOrPDM;

   public PDEPDM()
   {
   }

   public java.util.List<java.lang.String> getPdeOrPDM()
   {
      return this.pdeOrPDM;
   }

   public void setPdeOrPDM(java.util.List<java.lang.String> pdeOrPDM)
   {
      this.pdeOrPDM = pdeOrPDM;
   }

   public PDEPDM(java.util.List<java.lang.String> pdeOrPDM)
   {
      this.pdeOrPDM = pdeOrPDM;
   }

}