package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class Product implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String vendorName;
   private java.lang.String productName;
   private java.lang.String productVersion;

   public Product()
   {
   }

   public java.lang.String getVendorName()
   {
      return this.vendorName;
   }

   public void setVendorName(java.lang.String vendorName)
   {
      this.vendorName = vendorName;
   }

   public java.lang.String getProductName()
   {
      return this.productName;
   }

   public void setProductName(java.lang.String productName)
   {
      this.productName = productName;
   }

   public java.lang.String getProductVersion()
   {
      return this.productVersion;
   }

   public void setProductVersion(java.lang.String productVersion)
   {
      this.productVersion = productVersion;
   }

   public Product(java.lang.String vendorName, java.lang.String productName,
         java.lang.String productVersion)
   {
      this.vendorName = vendorName;
      this.productName = productName;
      this.productVersion = productVersion;
   }

}