package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class RoutingInstruction implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private String routingFunction;
   private java.lang.String routingPoint;
   private String routingStep;

   public RoutingInstruction()
   {
   }

   public java.lang.String getRoutingPoint()
   {
      return this.routingPoint;
   }

   public void setRoutingPoint(java.lang.String routingPoint)
   {
      this.routingPoint = routingPoint;
   }

   public java.lang.String getRoutingFunction()
   {
      return this.routingFunction;
   }

   public void setRoutingFunction(java.lang.String routingFunction)
   {
      this.routingFunction = routingFunction;
   }

   public java.lang.String getRoutingStep()
   {
      return this.routingStep;
   }

   public void setRoutingStep(java.lang.String routingStep)
   {
      this.routingStep = routingStep;
   }

   public RoutingInstruction(java.lang.String routingFunction,
         java.lang.String routingPoint, java.lang.String routingStep)
   {
      this.routingFunction = routingFunction;
      this.routingPoint = routingPoint;
      this.routingStep = routingStep;
   }

}