package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SecurityInfo implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.Boolean isSigningRequested;
   private java.lang.String rmaResult;
   private enisis.server.exchange.model.pduV202.FINSecurityInfo finSecurityInfo;

   private enisis.server.exchange.model.pduV202.ExchangeSecurityInfo exchangeSecurityInfo;

   public SecurityInfo()
   {
   }

   public java.lang.Boolean getIsSigningRequested()
   {
      return this.isSigningRequested;
   }

   public void setIsSigningRequested(java.lang.Boolean isSigningRequested)
   {
      this.isSigningRequested = isSigningRequested;
   }

   public java.lang.String getRmaResult()
   {
      return this.rmaResult;
   }

   public void setRmaResult(java.lang.String rmaResult)
   {
      this.rmaResult = rmaResult;
   }

   public enisis.server.exchange.model.pduV202.FINSecurityInfo getFinSecurityInfo()
   {
      return this.finSecurityInfo;
   }

   public void setFinSecurityInfo(
         enisis.server.exchange.model.pduV202.FINSecurityInfo finSecurityInfo)
   {
      this.finSecurityInfo = finSecurityInfo;
   }

   public enisis.server.exchange.model.pduV202.ExchangeSecurityInfo getExchangeSecurityInfo()
   {
      return this.exchangeSecurityInfo;
   }

   public void setExchangeSecurityInfo(
         enisis.server.exchange.model.pduV202.ExchangeSecurityInfo exchangeSecurityInfo)
   {
      this.exchangeSecurityInfo = exchangeSecurityInfo;
   }

   public SecurityInfo(
         java.lang.Boolean isSigningRequested,
         java.lang.String rmaResult,
         enisis.server.exchange.model.pduV202.FINSecurityInfo finSecurityInfo,
         enisis.server.exchange.model.pduV202.ExchangeSecurityInfo exchangeSecurityInfo)
   {
      this.isSigningRequested = isSigningRequested;
      this.rmaResult = rmaResult;
      this.finSecurityInfo = finSecurityInfo;
      this.exchangeSecurityInfo = exchangeSecurityInfo;
   }

}