package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SessionStatus implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.lang.String messagePartner;
   private java.lang.String creationTime;
   private java.lang.Integer sessionNr;
   private java.lang.String inputFile;
   private java.lang.Boolean isSuccess;
   private java.lang.String errorCode;
   private java.lang.String errorTextsessionDirection;
   private java.lang.String sessionDirection;
   private java.lang.Long accepted;
   private java.lang.Long rejected;
   private java.lang.Long acceptedFromMessagePartner;
   private java.lang.Long rejectedFromMessagePartner;
   private java.lang.Long acceptedToMessagePartner;
   private java.lang.Long rejectedToMessagePartner;

   public SessionStatus()
   {
   }

   public java.lang.String getMessagePartner()
   {
      return this.messagePartner;
   }

   public void setMessagePartner(java.lang.String messagePartner)
   {
      this.messagePartner = messagePartner;
   }

   public java.lang.String getCreationTime()
   {
      return this.creationTime;
   }

   public void setCreationTime(java.lang.String creationTime)
   {
      this.creationTime = creationTime;
   }

   public java.lang.Integer getSessionNr()
   {
      return this.sessionNr;
   }

   public void setSessionNr(java.lang.Integer sessionNr)
   {
      this.sessionNr = sessionNr;
   }

   public java.lang.String getInputFile()
   {
      return this.inputFile;
   }

   public void setInputFile(java.lang.String inputFile)
   {
      this.inputFile = inputFile;
   }

   public java.lang.Boolean getIsSuccess()
   {
      return this.isSuccess;
   }

   public void setIsSuccess(java.lang.Boolean isSuccess)
   {
      this.isSuccess = isSuccess;
   }

   public java.lang.String getErrorCode()
   {
      return this.errorCode;
   }

   public void setErrorCode(java.lang.String errorCode)
   {
      this.errorCode = errorCode;
   }

   public java.lang.String getErrorTextsessionDirection()
   {
      return this.errorTextsessionDirection;
   }

   public void setErrorTextsessionDirection(
         java.lang.String errorTextsessionDirection)
   {
      this.errorTextsessionDirection = errorTextsessionDirection;
   }

   public java.lang.String getSessionDirection()
   {
      return this.sessionDirection;
   }

   public void setSessionDirection(java.lang.String sessionDirection)
   {
      this.sessionDirection = sessionDirection;
   }

   public java.lang.Long getAccepted()
   {
      return this.accepted;
   }

   public void setAccepted(java.lang.Long accepted)
   {
      this.accepted = accepted;
   }

   public java.lang.Long getRejected()
   {
      return this.rejected;
   }

   public void setRejected(java.lang.Long rejected)
   {
      this.rejected = rejected;
   }

   public java.lang.Long getAcceptedFromMessagePartner()
   {
      return this.acceptedFromMessagePartner;
   }

   public void setAcceptedFromMessagePartner(
         java.lang.Long acceptedFromMessagePartner)
   {
      this.acceptedFromMessagePartner = acceptedFromMessagePartner;
   }

   public java.lang.Long getRejectedFromMessagePartner()
   {
      return this.rejectedFromMessagePartner;
   }

   public void setRejectedFromMessagePartner(
         java.lang.Long rejectedFromMessagePartner)
   {
      this.rejectedFromMessagePartner = rejectedFromMessagePartner;
   }

   public java.lang.Long getAcceptedToMessagePartner()
   {
      return this.acceptedToMessagePartner;
   }

   public void setAcceptedToMessagePartner(
         java.lang.Long acceptedToMessagePartner)
   {
      this.acceptedToMessagePartner = acceptedToMessagePartner;
   }

   public java.lang.Long getRejectedToMessagePartner()
   {
      return this.rejectedToMessagePartner;
   }

   public void setRejectedToMessagePartner(
         java.lang.Long rejectedToMessagePartner)
   {
      this.rejectedToMessagePartner = rejectedToMessagePartner;
   }

   public SessionStatus(java.lang.String messagePartner,
         java.lang.String creationTime, java.lang.Integer sessionNr,
         java.lang.String inputFile, java.lang.Boolean isSuccess,
         java.lang.String errorCode,
         java.lang.String errorTextsessionDirection,
         java.lang.String sessionDirection, java.lang.Long accepted,
         java.lang.Long rejected, java.lang.Long acceptedFromMessagePartner,
         java.lang.Long rejectedFromMessagePartner,
         java.lang.Long acceptedToMessagePartner,
         java.lang.Long rejectedToMessagePartner)
   {
      this.messagePartner = messagePartner;
      this.creationTime = creationTime;
      this.sessionNr = sessionNr;
      this.inputFile = inputFile;
      this.isSuccess = isSuccess;
      this.errorCode = errorCode;
      this.errorTextsessionDirection = errorTextsessionDirection;
      this.sessionDirection = sessionDirection;
      this.accepted = accepted;
      this.rejected = rejected;
      this.acceptedFromMessagePartner = acceptedFromMessagePartner;
      this.rejectedFromMessagePartner = rejectedFromMessagePartner;
      this.acceptedToMessagePartner = acceptedToMessagePartner;
      this.rejectedToMessagePartner = rejectedToMessagePartner;
   }

}