package enisis.server.exchange.model.pduV202;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class SignatureValue implements java.io.Serializable
{

   static final long serialVersionUID = 1L;

   private java.util.List<java.lang.String> content;

   public SignatureValue()
   {
   }

   public java.util.List<java.lang.String> getContent()
   {
      return this.content;
   }

   public void setContent(java.util.List<java.lang.String> content)
   {
      this.content = content;
   }

   public SignatureValue(java.util.List<java.lang.String> content)
   {
      this.content = content;
   }

}